#!/usr/bin/env bash
# The next cli interact (ninteract)
# Installed via envrc

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
PROJECT_DIR=$(realpath "$SCRIPT_DIR/../..")
# TSX_TSCONFIG_PATH="$PROJECT_DIR/tsconfig.json"
tsx "$PROJECT_DIR/src/interact/cli/dev.js" "$@"
